routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('create_payment', 'PaymentController@create_payment');
Route::post('create_payment', 'PaymentController@store_payment');
Route::get('confirm_code/{order_id}', ['as' => 'get.confirm.code', 'uses' => 'PaymentController@confirm_code']);
Route::post('confirm_code/{order_id}', 'PaymentController@finish_payment');

Route::get('send_notification_queue/{token}/{title}/{message}/{type}',"NotificationController@send_notification_queue");
Route::post('notifications/store',"NotificationController@store");

Auth::routes();
Route::group([ 'middleware' => ['auth'] ], function () {

	Route::resource("schedules","ScheduleController");
	Route::resource("packages","PackageController");
	Route::resource("orders","OrderController");

	Route::resource("doctors","DoctorController");
	Route::resource("patients","PatientController");

	Route::resource("durations","DurationController");
	Route::get('/home', 'HomeController@index');

	Route::resource("days","DayController");
	Route::resource("feedback","FeedbackController");
	Route::resource("promo_codes","PromoCodeController");
	Route::resource("CountryCity","CountryCityController");

	Route::get('notifications/create', function () {
	    return view('notifications.create');
	});


	Route::get("searchCustomer/{key}","AuthController@search_users");

	//======================<< fawzy  >>=========================================
	Route::get('GetDoctorCredit/{user_id}',"DoctorController@GetDoctorCredit");
	Route::get('viewScheduleHistory/{week}',"ScheduleController@getScheduleHistory");
	//Route::get("intialSchedualDoctors","ScheduleController@intialSchedualDoctors");
	Route::get("showScheduleHistory/{doctor_id}/{startweekDate}","DoctorController@showScheduleHistory");

	Route::get("previousCalls/{doctor_id}","DoctorController@previousCalls");
	Route::get("previousCallsDetails/{order_id}","DoctorController@previousCallsDetails");
	Route::get("AjaxBlock/{key}","DoctorController@AjaxBlock");


	Route::get("patientpreviousCalls/{patient_id}","PatientController@previousCalls");
	Route::get("patientpreviousCallsDetails/{patient_id}","PatientController@previousCallsDetails");
	Route::get("patientAjaxBlock/{patient_id}","PatientController@AjaxBlock");
	Route::get("PackageHistory/{patient_id}","PatientController@PackageHistory");

	Route::get("EditPackageHistory/{package_id}","PatientController@EditPackageHistory");
	Route::post("storeEditPackageHistory","PatientController@storeEditPackageHistory");

	Route::get("filterOrders","OrderController@filterOrders");

	Route::get("AdminDashboard","DoctorController@dashboard");
	Route::get("/","DoctorController@dashboard");

});

//====================================<< History >>======================================
Route::get('scheduleHistory',"ScheduleController@scheduleHistory");
Route::get('creditHistory',"ScheduleController@creditHistory");
Route::get('totalCreditHistory/{doctor_id}',"DoctorController@totalCreditHistory");

app/PromoCode.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PromoCode extends Model
{
    //
    protected $hidden =['updated_at'];
}

app/User.php
<?php

namespace App;
use Hash;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    protected $primaryKey = 'id';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','mobile','is_block','image','version','platform','type'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token','type','updated_at'
    ];
     #hash password
    public function setPasswordAttribute($pass)
    {
           $this->attributes['password'] = Hash::make($pass);
    }


    public function orders()
    {
        return $this->belongsToMany(\App\Order::class, 'order_doctors', 'user_id', 'order_id');
    }

    public function acceptedOrders()
    {
        return $this->orders()->wherePivot('is_accept', 1)->count();
    }

    public function unacceptedOrders()
    {
        return $this->orders()->wherePivot('is_accept', 0)->count();
    }

    public function getImageAttribute($value)
    {
        if($value != ""){
            $value=url("/")."/public/images/users/".$value;
        }
        return $value;
    }
    public function getcreatedAtAttribute($value)
    {
       return \Carbon\Carbon::parse($value)->format('d F Y h:i A');
    }

}

app/Http/Controllers/PromoCodeController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\PromoCode;
use Illuminate\Http\Request;

class PromoCodeController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$promo_codes = PromoCode::orderBy('id', 'desc')->get();

		return view('promo_codes.index', compact('promo_codes'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('promo_codes.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store(Request $request)
	{
		$this->validate($request, [
	        'code' => 'required|unique:promo_codes|max:255',
	        'type' => 'required',
    	]);
		$promo_code = new PromoCode();

		$promo_code->code = $request->input("code");
        $promo_code->status = $request->input("status");
        $promo_code->type = $request->input("type");
        if ( $request->input("discount") == null ) {
        	$promo_code->discount = 0;
        }else{
        	$promo_code->discount = $request->input("discount");
        }

		$promo_code->save();

		return redirect()->route('promo_codes.index')->with('message', 'Item created successfully.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$promo_code = PromoCode::findOrFail($id);

		return view('promo_codes.show', compact('promo_code'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$promo_code = PromoCode::findOrFail($id);

		return view('promo_codes.edit', compact('promo_code'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @param Request $request
	 * @return Response
	 */
	public function update(Request $request, $id)
	{
		$promo_code = PromoCode::findOrFail($id);

		$promo_code->code = $request->input("code");
        $promo_code->status = $request->input("status");
        $promo_code->type = $request->input("type");
        $promo_code->discount = $request->input("discount");

		$promo_code->save();

		return redirect()->route('promo_codes.index')->with('message', 'Item updated successfully.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$promo_code = PromoCode::findOrFail($id);
		$promo_code->delete();

		return redirect()->route('promo_codes.index')->with('message', 'Item deleted successfully.');
	}

}

resources/views/promo_codes/create.blade.php
@extends('layouts.admin')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
    <div class="page-header">
        <h3><i class="glyphicon glyphicon-plus"></i> PromoCodes / Create </h3>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('promo_codes.store') }}" method="POST">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('code')) has-error @endif">
                       <label class="col-sm-2 control-label" for="code-field">Code</label>
                    <input type="text" id="code-field" name="code" class="form-control" value="{{ old("code") }}"/>
                       @if($errors->has("code"))
                        <span class="help-block">{{ $errors->first("code") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('status')) has-error @endif">
                       <label class="col-sm-2 control-label" for="status-field">Status</label>
                    
                      <select id="status-field" name="status" class="form-control" >
                        <option {{ old("status") == 0 ? 'selected' : '' }} value="0">Available</option>
                        <option {{ old("status") == 1 ? 'selected' : '' }} value="1">Not Available</option>
                    </select>

                       @if($errors->has("status"))
                        <span class="help-block">{{ $errors->first("status") }}</span>
                       @endif
                    </div>
                     <div class="form-group @if($errors->has('type')) has-error @endif">
                       <label class="col-sm-2 control-label" for="type-field">type</label>
                    <select id="type-field" name="type" class="form-control" >
                        <option {{ old("type") == 0 ? 'selected' : '' }} value="0">Free</option>
                        <option {{ old("type") == 1 ? 'selected' : '' }} value="1">Discount</option>
                    </select>
                       @if($errors->has("type"))
                        <span class="help-block">{{ $errors->first("type") }}</span>
                       @endif
                    </div>
                     <div id="discount" class="form-group @if($errors->has('discount')) has-error @endif">
                       <label class="col-sm-2 control-label" for="discount-field">discount</label>
                    <input type="number" id="discount-field" name="discount" class="form-control" value="{{ old("discount") }}"/>
                       @if($errors->has("discount"))
                        <span class="help-block">{{ $errors->first("discount") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a class="btn btn-link pull-right" href="{{ route('promo_codes.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
  if($("#type-field").val() == "1"){
        $("#discount").show();
      }else{
        $("#discount").hide();

      }
    $("#type-field").on("change",function(){
      if($("#type-field").val() == "1"){
        $("#discount").show();
      }else{
        $("#discount").hide();

      }
    });
  </script>
@endsection

resources/views/promo_codes/edit.blade.php
@extends('layouts.admin')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
    <div class="page-header">
        <h3><i class="glyphicon glyphicon-edit"></i> PromoCodes / Edit #{{$promo_code->id}}</h3>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('promo_codes.update', $promo_code->id) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('code')) has-error @endif">
                       <label class="col-sm-2 control-label" for="code-field">Code</label>
                    <input type="text" id="code-field" name="code" class="form-control" value="{{ is_null(old("code")) ? $promo_code->code : old("code") }}"/>
                       @if($errors->has("code"))
                        <span class="help-block">{{ $errors->first("code") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('status')) has-error @endif">
                       <label class="col-sm-2 control-label" for="status-field">Status</label>
                    
                      <select id="status-field" name="status" class="form-control" >
                        <option {{ is_null(old("status")) ? $promo_code->status : old("status") == 0 ? 'selected' : '' }} value="0">Available</option>
                        <option {{ is_null(old("status")) ? $promo_code->status : old("status") == 1 ? 'selected' : '' }} value="1">Not Available</option>
                    </select>

                       @if($errors->has("status"))
                        <span class="help-block">{{ $errors->first("status") }}</span>
                       @endif
                    </div>
                     <div class="form-group @if($errors->has('type')) has-error @endif">
                       <label class="col-sm-2 control-label" for="type-field">type</label>
                    <select id="type-field" name="type" class="form-control" >
                        <option {{ is_null(old("type")) ? $promo_code->type : old("type") == 0 ? 'selected' : '' }} value="0">Free</option>
                        <option {{ is_null(old("type")) ? $promo_code->type : old("type") == 1 ? 'selected' : '' }} value="1">Discount</option>
                    </select>
                       @if($errors->has("type"))
                        <span class="help-block">{{ $errors->first("type") }}</span>
                       @endif
                    </div>
                     <div id="discount" class="form-group @if($errors->has('discount')) has-error @endif">
                       <label class="col-sm-2 control-label" for="discount-field">discount</label>
                    <input type="number" id="discount-field" name="discount" class="form-control" value="{{ is_null(old("discount")) ? $promo_code->discount : old("discount") }}"/>
                       @if($errors->has("discount"))
                        <span class="help-block">{{ $errors->first("discount") }}</span>
                       @endif
                    </div>

                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a class="btn btn-link pull-right" href="{{ route('promo_codes.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
    });
  </script>
@endsection

resources/views/promo_codes/index.blade.php
@extends('layouts.admin')

@section('header')
    <div class="page-header clearfix">
        <h3>
            <i class="glyphicon glyphicon-align-justify"></i> PromoCodes
            <a class="btn btn-success pull-right" href="{{ route('promo_codes.create') }}"><i class="glyphicon glyphicon-plus"></i> Create</a>
        </h3>

    </div>
@endsection
<?php  use App\UserPackage; ?>
@section('content')
    <div class="row">
        <div class="col-md-12">
            @if($promo_codes->count())
                <table id="datatable" class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>CODE</th>
                        <th>STATUS</th>
                        <th>TYPE</th>
                        <th>DISCOUNT</th>
                        <th>Use Count</th>
                        <th>Created_at</th>
                            <th class="text-right">OPTIONS</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($promo_codes as $promo_code)
                            <tr>
                                <td>{{$promo_code->id}}</td>
                                <td>{{$promo_code->code}}</td>
                    <td>@if( $promo_code->status == 0 ) Available @else Not Available @endif</td>
                    <td>@if( $promo_code->type == 0 ) Free @else Discount @endif</td>
                    <td>{{$promo_code->discount}}</td>
                    <td>{{ UserPackage::where('promo_code_id' , $promo_code->id )->count() }}</td>
                     <td>{{$promo_code->created_at}}</td>
                                <td class="text-right">
                                    <a class="btn btn-xs btn-primary" href="{{ route('promo_codes.show', $promo_code->id) }}"><i class="glyphicon glyphicon-eye-open"></i> View</a>
                                    <a class="btn btn-xs btn-warning" href="{{ route('promo_codes.edit', $promo_code->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                                    <form action="{{ route('promo_codes.destroy', $promo_code->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif

        </div>
    </div>

@endsection

resources/views/promo_codes/show.blade.php
@extends('layouts.admin')
@section('header')
<div class="page-header">
        <h3>PromoCodes / Show #{{$promo_code->id}}</h3>
        <form action="{{ route('promo_codes.destroy', $promo_code->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="btn-group pull-right" role="group" aria-label="...">
                <a class="btn btn-warning btn-group" role="group" href="{{ route('promo_codes.edit', $promo_code->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">

            <form action="#">
                <div class="form-group">
                    <label for="nome">ID</label>
                    <p class="form-control-static"></p>
                </div>
                <div class="form-group">
                     <label for="code">CODE</label>
                     <p class="form-control-static">{{$promo_code->code}}</p>
                </div>
                    <div class="form-group">
                     <label for="status">STATUS</label>
                     <p class="form-control-static">{{$promo_code->status}}</p>
                </div>
                </div>
                    <div class="form-group">
                     <label for="status" class="control-label">Created at</label>
                     <p class="form-control-static">{{$promo_code->created_at}}</p>
                </div>

            </form>

            <a class="btn btn-link" href="{{ route('promo_codes.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>

        </div>
    </div>

@endsection