routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('create_payment', 'PaymentController@create_payment');
Route::post('create_payment', 'PaymentController@store_payment');
Route::get('confirm_code/{order_id}', ['as' => 'get.confirm.code', 'uses' => 'PaymentController@confirm_code']);
Route::post('confirm_code/{order_id}', 'PaymentController@finish_payment');

Route::get('send_notification_queue/{token}/{title}/{message}/{type}',"NotificationController@send_notification_queue");
Route::post('notifications/store',"NotificationController@store");

Auth::routes();
Route::group([ 'middleware' => ['auth'] ], function () {

	Route::resource("schedules","ScheduleController");
	Route::resource("packages","PackageController");
	Route::resource("orders","OrderController");

	Route::resource("doctors","DoctorController");
	Route::resource("patients","PatientController");

	Route::resource("durations","DurationController");
	Route::get('/home', 'HomeController@index');

	Route::resource("days","DayController");
	Route::resource("feedback","FeedbackController");
	Route::resource("promo_codes","PromoCodeController");
	Route::resource("CountryCity","CountryCityController");

	Route::get('notifications/create', function () {
	    return view('notifications.create');
	});


	Route::get("searchCustomer/{key}","AuthController@search_users");

	//======================<< fawzy  >>=========================================
	Route::get('GetDoctorCredit/{user_id}',"DoctorController@GetDoctorCredit");
	Route::get('viewScheduleHistory/{week}',"ScheduleController@getScheduleHistory");
	//Route::get("intialSchedualDoctors","ScheduleController@intialSchedualDoctors");
	Route::get("showScheduleHistory/{doctor_id}/{startweekDate}","DoctorController@showScheduleHistory");

	Route::get("previousCalls/{doctor_id}","DoctorController@previousCalls");
	Route::get("previousCallsDetails/{order_id}","DoctorController@previousCallsDetails");
	Route::get("AjaxBlock/{key}","DoctorController@AjaxBlock");


	Route::get("patientpreviousCalls/{patient_id}","PatientController@previousCalls");
	Route::get("patientpreviousCallsDetails/{patient_id}","PatientController@previousCallsDetails");
	Route::get("patientAjaxBlock/{patient_id}","PatientController@AjaxBlock");
	Route::get("PackageHistory/{patient_id}","PatientController@PackageHistory");

	Route::get("EditPackageHistory/{package_id}","PatientController@EditPackageHistory");
	Route::post("storeEditPackageHistory","PatientController@storeEditPackageHistory");

	Route::get("filterOrders","OrderController@filterOrders");

	Route::get("AdminDashboard","DoctorController@dashboard");
	Route::get("/","DoctorController@dashboard");

});

//====================================<< History >>======================================
Route::get('scheduleHistory',"ScheduleController@scheduleHistory");
Route::get('creditHistory',"ScheduleController@creditHistory");
Route::get('totalCreditHistory/{doctor_id}',"DoctorController@totalCreditHistory");

app/City.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class City extends Model
{

    protected $primaryKey = 'id';
    protected $table = 'cities';
    protected $hidden = [ 'created_at', 'updated_at' , 'country_id'];


    public function Country()
    {
        return $this->belongsTo('App\Country' , 'country_id');
    }

}

app/User.php
<?php

namespace App;
use Hash;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    protected $primaryKey = 'id';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','mobile','is_block','image','version','platform','type'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token','type','updated_at'
    ];
     #hash password
    public function setPasswordAttribute($pass)
    {
           $this->attributes['password'] = Hash::make($pass);
    }


    public function orders()
    {
        return $this->belongsToMany(\App\Order::class, 'order_doctors', 'user_id', 'order_id');
    }

    public function acceptedOrders()
    {
        return $this->orders()->wherePivot('is_accept', 1)->count();
    }

    public function unacceptedOrders()
    {
        return $this->orders()->wherePivot('is_accept', 0)->count();
    }

    public function getImageAttribute($value)
    {
        if($value != ""){
            $value=url("/")."/public/images/users/".$value;
        }
        return $value;
    }
    public function getcreatedAtAttribute($value)
    {
       return \Carbon\Carbon::parse($value)->format('d F Y h:i A');
    }

}

resources/views/cities/create.blade.php
@extends('layouts.admin')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
    <div class="page-header">
        <h3><i class="glyphicon glyphicon-plus"></i> Cities / Create </h3>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('CountryCity.store') }}" method="POST">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                  <div class="form-group @if($errors->has('name')) has-error @endif">
                       <label class="col-sm-2 control-label" for="code-field">City Name</label>
                       <input required="please enter city name" type="text" id="code-field" name="name" class="form-control" value="{{ old("name") }}"/>
                       @if($errors->has("name"))
                        <span class="help-block">{{ $errors->first("name") }}</span>
                       @endif
                  </div>


                  <div class="form-group @if($errors->has('country_id')) has-error @endif">
                     <label class="col-sm-2 control-label" for="status-field">Country</label>
                    <select id="status-field" name="country_id" class="form-control" >
                      @foreach($countries as $country)
                          <option value="{{$country->id}}">{{$country->name}}</option>
                      @endforeach
                    </select>
                     @if($errors->has("country_id"))
                      <span class="help-block">{{ $errors->first("country_id") }}</span>
                     @endif
                  </div>

                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a class="btn btn-link pull-right" href="{{ route('CountryCity.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
<!--   <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
  if($("#type-field").val() == "1"){
        $("#discount").show();
      }else{
        $("#discount").hide();

      }
    $("#type-field").on("change",function(){
      if($("#type-field").val() == "1"){
        $("#discount").show();
      }else{
        $("#discount").hide();

      }
    });
  </script> -->
@endsection

resources/views/cities/edit.blade.php
@extends('layouts.admin')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
    <div class="page-header">
        <h3><i class="glyphicon glyphicon-plus"></i> Cities / Create </h3>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

           <form action="{{ route('CountryCity.update', $CountryCity->id) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                  <div class="form-group @if($errors->has('name')) has-error @endif">
                       <label class="col-sm-2 control-label" for="code-field">City Name</label>
                       <input required="please enter city name" type="text" id="code-field" name="name" class="form-control" value="{{ is_null(old("name")) ? $CountryCity->name : old("name") }}" />
                       @if($errors->has("name"))
                        <span class="help-block">{{ $errors->first("name") }}</span>
                       @endif
                  </div>


                  <div class="form-group @if($errors->has('country_id')) has-error @endif">
                     <label class="col-sm-2 control-label" for="status-field">Country</label>
                    <select id="status-field" name="country_id" class="form-control" >
                      @foreach($countries as $country)
                        @if($country->id == $CountryCity->country_id)
                          <option value="{{$country->id}}" selected>{{$country->name}}</option>
                        @else
                          <option value="{{$country->id}}">{{$country->name}}</option>
                        @endif  
                      @endforeach
                    </select>
                     @if($errors->has("country_id"))
                      <span class="help-block">{{ $errors->first("country_id") }}</span>
                     @endif
                  </div>

                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a class="btn btn-link pull-right" href="{{ route('CountryCity.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
<!--   <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
  if($("#type-field").val() == "1"){
        $("#discount").show();
      }else{
        $("#discount").hide();

      }
    $("#type-field").on("change",function(){
      if($("#type-field").val() == "1"){
        $("#discount").show();
      }else{
        $("#discount").hide();

      }
    });
  </script> -->
@endsection

resources/views/cities/index.blade.php
@extends('layouts.admin')

@section('header')
    <div class="page-header clearfix">
        <h3>
            <i class="glyphicon glyphicon-align-justify"></i> Cities
            <a class="btn btn-success pull-right" href="{{ route('CountryCity.create') }}"><i class="glyphicon glyphicon-plus"></i> Create</a>
        </h3>

    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            @if($CountryCity->count())
                <table id="datatable" class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>City Name</th>
                            <th>Country Name</th>
                            <th>Created_at</th>
                            <th class="text-right">OPTIONS</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($CountryCity as $city)
                            <tr>
                                <td>{{$city->id}}</td>
                                <td>{{$city->name}}</td>
                                <td>{{$city->Country->name}}</td>
                                <td>{{$city->created_at}}</td>
                                <td class="text-right">
                                    <a class="btn btn-xs btn-primary" href="{{ route('CountryCity.show', $city->id) }}"><i class="glyphicon glyphicon-eye-open"></i> View</a>
                                    <a class="btn btn-xs btn-warning" href="{{ route('CountryCity.edit', $city->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                                    <form action="{{ route('CountryCity.destroy', $city->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif

        </div>
    </div>

@endsection

resources/views/cities/show.blade.php
@extends('layouts.admin')
@section('header')
<div class="page-header">
        <h3>Cities / Show #{{$CountryCity->id}}</h3>
        <form action="{{ route('CountryCity.destroy', $CountryCity->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="btn-group pull-right" role="group" aria-label="...">
                <a class="btn btn-warning btn-group" role="group" href="{{ route('CountryCity.edit', $CountryCity->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">

            <form action="#">
                <div class="form-group">
                    <label for="nome">ID</label>
                    <p class="form-control-static">{{$CountryCity->id}}</p>
                </div>
                <div class="form-group">
                     <label for="code">City Name</label>
                     <p class="form-control-static">{{$CountryCity->name}}</p>
                </div>
                    <div class="form-group">
                     <label for="status">Country Name</label>
                     <p class="form-control-static">{{$CountryCity->Country->name}}</p>
                </div>

                </div>
                    <div class="form-group">
                     <label for="status">Created at</label>
                     <p class="form-control-static">{{$CountryCity->created_at}}</p>
                </div>

            </form>

            <a class="btn btn-link" href="{{ route('CountryCity.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>

        </div>
    </div>

@endsection