routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('create_payment', 'PaymentController@create_payment');
Route::post('create_payment', 'PaymentController@store_payment');
Route::get('confirm_code/{order_id}', ['as' => 'get.confirm.code', 'uses' => 'PaymentController@confirm_code']);
Route::post('confirm_code/{order_id}', 'PaymentController@finish_payment');

Route::get('send_notification_queue/{token}/{title}/{message}/{type}',"NotificationController@send_notification_queue");
Route::post('notifications/store',"NotificationController@store");

Auth::routes();
Route::group([ 'middleware' => ['auth'] ], function () {

	Route::resource("schedules","ScheduleController");
	Route::resource("packages","PackageController");
	Route::resource("orders","OrderController");

	Route::resource("doctors","DoctorController");
	Route::resource("patients","PatientController");

	Route::resource("durations","DurationController");
	Route::get('/home', 'HomeController@index');

	Route::resource("days","DayController");
	Route::resource("feedback","FeedbackController");
	Route::resource("promo_codes","PromoCodeController");
	Route::resource("CountryCity","CountryCityController");

	Route::get('notifications/create', function () {
	    return view('notifications.create');
	});


	Route::get("searchCustomer/{key}","AuthController@search_users");

	//======================<< fawzy  >>=========================================
	Route::get('GetDoctorCredit/{user_id}',"DoctorController@GetDoctorCredit");
	Route::get('viewScheduleHistory/{week}',"ScheduleController@getScheduleHistory");
	//Route::get("intialSchedualDoctors","ScheduleController@intialSchedualDoctors");
	Route::get("showScheduleHistory/{doctor_id}/{startweekDate}","DoctorController@showScheduleHistory");

	Route::get("previousCalls/{doctor_id}","DoctorController@previousCalls");
	Route::get("previousCallsDetails/{order_id}","DoctorController@previousCallsDetails");
	Route::get("AjaxBlock/{key}","DoctorController@AjaxBlock");


	Route::get("patientpreviousCalls/{patient_id}","PatientController@previousCalls");
	Route::get("patientpreviousCallsDetails/{patient_id}","PatientController@previousCallsDetails");
	Route::get("patientAjaxBlock/{patient_id}","PatientController@AjaxBlock");
	Route::get("PackageHistory/{patient_id}","PatientController@PackageHistory");

	Route::get("EditPackageHistory/{package_id}","PatientController@EditPackageHistory");
	Route::post("storeEditPackageHistory","PatientController@storeEditPackageHistory");

	Route::get("filterOrders","OrderController@filterOrders");

	Route::get("AdminDashboard","DoctorController@dashboard");
	Route::get("/","DoctorController@dashboard");

});

//====================================<< History >>======================================
Route::get('scheduleHistory',"ScheduleController@scheduleHistory");
Route::get('creditHistory',"ScheduleController@creditHistory");
Route::get('totalCreditHistory/{doctor_id}',"DoctorController@totalCreditHistory");

app/Feedback.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Feedback extends Model
{
    //

   /* public function user()
    {
           return $this->belongsTo('App\User','email');
    }
    */
    protected $appends = array('user');
    public function getUserAttribute()
    {
            $user = User::where('email',$this->email)->first();

        return $user; 
    }
}

app/User.php
<?php

namespace App;
use Hash;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    protected $primaryKey = 'id';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','mobile','is_block','image','version','platform','type'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token','type','updated_at'
    ];
     #hash password
    public function setPasswordAttribute($pass)
    {
           $this->attributes['password'] = Hash::make($pass);
    }


    public function orders()
    {
        return $this->belongsToMany(\App\Order::class, 'order_doctors', 'user_id', 'order_id');
    }

    public function acceptedOrders()
    {
        return $this->orders()->wherePivot('is_accept', 1)->count();
    }

    public function unacceptedOrders()
    {
        return $this->orders()->wherePivot('is_accept', 0)->count();
    }

    public function getImageAttribute($value)
    {
        if($value != ""){
            $value=url("/")."/public/images/users/".$value;
        }
        return $value;
    }
    public function getcreatedAtAttribute($value)
    {
       return \Carbon\Carbon::parse($value)->format('d F Y h:i A');
    }

}

app/Http/Controllers/FeedbackController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Feedback;
use Illuminate\Http\Request;

class FeedbackController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$feedbacks = Feedback::orderBy('id', 'desc')->get();

		return view('feedback.index', compact('feedbacks'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('feedback.create');
	}
	
	
	public function send_feedback(Request $request)
	{

		if(! isset($request->email)){
    		$statusCode = 420;
			$response  = array('msg' => 'Invalid Format!');
			return response()->json($response, $statusCode);

		}elseif(! isset($request->subject)){
			$statusCode = 420;
    		$response  = array('msg' => 'Invalid Format !');
    		return response()->json($response, $statusCode);

		}elseif(! isset($request->body)){
			$statusCode = 420;
    		$response  = array('msg' => 'Invalid Format !');
    		return response()->json($response, $statusCode);

		}else{
			$feedback = new Feedback();

			$feedback->subject = $request->subject;
	        $feedback->body = $request->body;
	        $feedback->email = $request->email;

			$feedback->save();
			$statusCode = 200;
    		$response  = array('msg' => 'Done!');
    		return response()->json($response, $statusCode);
		}

	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response send_feedback
	 */
	public function store(Request $request)
	{
		$feedback = new Feedback();

		$feedback->subject = $request->input("subject");
	        $feedback->body = $request->input("body");
	        $feedback->email = $request->input("email");

		$feedback->save();

		return redirect()->route('feedback.index')->with('message', 'Item created successfully.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$feedback = Feedback::findOrFail($id);

		return view('feedback.show', compact('feedback'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$feedback = Feedback::findOrFail($id);

		return view('feedback.edit', compact('feedback'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @param Request $request
	 * @return Response
	 */
	public function update(Request $request, $id)
	{
		$feedback = Feedback::findOrFail($id);

		$feedback->subject = $request->input("subject");
        $feedback->body = $request->input("body");
        $feedback->email = $request->input("email");

		$feedback->save();

		return redirect()->route('feedback.index')->with('message', 'Item updated successfully.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$feedback = Feedback::findOrFail($id);
		$feedback->delete();

		return redirect()->route('feedback.index')->with('message', 'Item deleted successfully.');
	}

}

resources/views/feedback/create.blade.php
@extends('layout')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-plus"></i> Feedback / Create </h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('feedback.store') }}" method="POST">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('subject')) has-error @endif">
                       <label for="subject-field">Subject</label>
                    <input type="text" id="subject-field" name="subject" class="form-control" value="{{ old("subject") }}"/>
                       @if($errors->has("subject"))
                        <span class="help-block">{{ $errors->first("subject") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('body')) has-error @endif">
                       <label for="body-field">Body</label>
                    <textarea class="form-control" id="body-field" rows="3" name="body">{{ old("body") }}</textarea>
                       @if($errors->has("body"))
                        <span class="help-block">{{ $errors->first("body") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('email')) has-error @endif">
                       <label for="email-field">Email</label>
                    <input type="text" id="email-field" name="email" class="form-control" value="{{ old("email") }}"/>
                       @if($errors->has("email"))
                        <span class="help-block">{{ $errors->first("email") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a class="btn btn-link pull-right" href="{{ route('feedback.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
    });
  </script>
@endsection

resources/views/feedback/edit.blade.php
@extends('layout')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-edit"></i> Feedback / Edit #{{$feedback->id}}</h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('feedback.update', $feedback->id) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('subject')) has-error @endif">
                       <label for="subject-field">Subject</label>
                    <input type="text" id="subject-field" name="subject" class="form-control" value="{{ is_null(old("subject")) ? $feedback->subject : old("subject") }}"/>
                       @if($errors->has("subject"))
                        <span class="help-block">{{ $errors->first("subject") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('body')) has-error @endif">
                       <label for="body-field">Body</label>
                    <textarea class="form-control" id="body-field" rows="3" name="body">{{ is_null(old("body")) ? $feedback->body : old("body") }}</textarea>
                       @if($errors->has("body"))
                        <span class="help-block">{{ $errors->first("body") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('email')) has-error @endif">
                       <label for="email-field">Email</label>
                    <input type="text" id="email-field" name="email" class="form-control" value="{{ is_null(old("email")) ? $feedback->email : old("email") }}"/>
                       @if($errors->has("email"))
                        <span class="help-block">{{ $errors->first("email") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a class="btn btn-link pull-right" href="{{ route('feedback.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
    });
  </script>
@endsection

resources/views/feedback/index.blade.php
<?php 
use App\Patient;
?>
@extends('layouts.admin')

@section('header')

@endsection

@section('content')
	    <div class="page-header clearfix">
        
        <h3>
        <i class="glyphicon glyphicon-align-justify"></i> Feedback
    </h3>
    </div>
            
    <div class="row">
        <div class="col-md-12 table-responsive" >
            @if($feedbacks->count())
                <table id="datatable" class="table table-striped table-bordered" style="table-layout: fixed; width: 100%">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th >SUBJECT</th>
                            <th>BODY</th>
                            <th>EMAIL</th>
                            <th>Created_at</th>
                            <th class="text-right">OPTIONS</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($feedbacks as $feedback)
                            <tr>
                                <td>{{$feedback->id}}</td>
                                <td>{{$feedback->subject}}</td>
                    <td><div style="word-wrap: break-word; " >{{$feedback->body}} </div></td>
                    <?php $user_id = Patient::where('user_id' , $feedback->user->id)->value("id"); ?>
                    <td>@if($feedback->user)<a href="{{URL::asset('patients/'.$user_id)}}">{{$feedback->email}}</a> @else {{$feedback->email}} @endif</td>
                    <td>{{$feedback->created_at}}</td>
                                <td class="text-right">
                                  
                                    <form action="{{ route('feedback.destroy', $feedback->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif

        </div>
    </div>

@endsection

resources/views/feedback/show.blade.php
@extends('layout')
@section('header')
<div class="page-header">
        <h1>Feedback / Show #{{$feedback->id}}</h1>
        <form action="{{ route('feedback.destroy', $feedback->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="btn-group pull-right" role="group" aria-label="...">
                <a class="btn btn-warning btn-group" role="group" href="{{ route('feedback.edit', $feedback->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">

            <form action="#">
                <div class="form-group">
                    <label for="nome">ID</label>
                    <p class="form-control-static"></p>
                </div>
                <div class="form-group">
                     <label for="subject">SUBJECT</label>
                     <p class="form-control-static">{{$feedback->subject}}</p>
                </div>
                    <div class="form-group">
                     <label for="body">BODY</label>
                     <p class="form-control-static">{{$feedback->body}}</p>
                </div>
                    <div class="form-group">
                     <label for="email">EMAIL</label>
                     <p class="form-control-static">{{$feedback->email}}</p>
                </div>
                </div>
                    <div class="form-group">
                     <label for="status" class="control-label">Created at</label>
                     <p class="form-control-static">{{$feedback->created_at}}</p>
                </d
                
            </form>

            <a class="btn btn-link" href="{{ route('feedback.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>

        </div>
    </div>

@endsection