routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('create_payment', 'PaymentController@create_payment');
Route::post('create_payment', 'PaymentController@store_payment');
Route::get('confirm_code/{order_id}', ['as' => 'get.confirm.code', 'uses' => 'PaymentController@confirm_code']);
Route::post('confirm_code/{order_id}', 'PaymentController@finish_payment');

Route::get('send_notification_queue/{token}/{title}/{message}/{type}',"NotificationController@send_notification_queue");
Route::post('notifications/store',"NotificationController@store");

Auth::routes();
Route::group([ 'middleware' => ['auth'] ], function () {

	Route::resource("schedules","ScheduleController");
	Route::resource("packages","PackageController");
	Route::resource("orders","OrderController");

	Route::resource("doctors","DoctorController");
	Route::resource("patients","PatientController");

	Route::resource("durations","DurationController");
	Route::get('/home', 'HomeController@index');

	Route::resource("days","DayController");
	Route::resource("feedback","FeedbackController");
	Route::resource("promo_codes","PromoCodeController");
	Route::resource("CountryCity","CountryCityController");

	Route::get('notifications/create', function () {
	    return view('notifications.create');
	});


	Route::get("searchCustomer/{key}","AuthController@search_users");

	//======================<< fawzy  >>=========================================
	Route::get('GetDoctorCredit/{user_id}',"DoctorController@GetDoctorCredit");
	Route::get('viewScheduleHistory/{week}',"ScheduleController@getScheduleHistory");
	//Route::get("intialSchedualDoctors","ScheduleController@intialSchedualDoctors");
	Route::get("showScheduleHistory/{doctor_id}/{startweekDate}","DoctorController@showScheduleHistory");

	Route::get("previousCalls/{doctor_id}","DoctorController@previousCalls");
	Route::get("previousCallsDetails/{order_id}","DoctorController@previousCallsDetails");
	Route::get("AjaxBlock/{key}","DoctorController@AjaxBlock");


	Route::get("patientpreviousCalls/{patient_id}","PatientController@previousCalls");
	Route::get("patientpreviousCallsDetails/{patient_id}","PatientController@previousCallsDetails");
	Route::get("patientAjaxBlock/{patient_id}","PatientController@AjaxBlock");
	Route::get("PackageHistory/{patient_id}","PatientController@PackageHistory");

	Route::get("EditPackageHistory/{package_id}","PatientController@EditPackageHistory");
	Route::post("storeEditPackageHistory","PatientController@storeEditPackageHistory");

	Route::get("filterOrders","OrderController@filterOrders");

	Route::get("AdminDashboard","DoctorController@dashboard");
	Route::get("/","DoctorController@dashboard");

});

//====================================<< History >>======================================
Route::get('scheduleHistory',"ScheduleController@scheduleHistory");
Route::get('creditHistory',"ScheduleController@creditHistory");
Route::get('totalCreditHistory/{doctor_id}',"DoctorController@totalCreditHistory");

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use JWTAuth;
class Order extends Model
{
    //
     protected $hidden = [
        'updated_at','user_id','duration_id','schedule_id'
    ];

  //  protected $dateFormat = 'd F Y';
    protected $appends = array('doctor','patient','patient_request','packageType','doctors_on_shift' , 'doctor_accept');


    public function doctors()
    {
      return $this->belongsToMany(\App\User::class, 'order_doctors', 'order_id', 'user_id');
    }

    public function getDoctorsOnShiftAttribute()
    {

      $doctor_ids = OrderDoctor::limit(2)->where("order_id",$this->id)->where('onShift' , 1)->orderBy('created_at','ASC')->pluck('user_id')->toArray();
      $doctors     = Doctor::whereIn('user_id',$doctor_ids)->get();
      return $doctors;

    }


    public function getDoctorAcceptAttribute()
    {

      // $doctor_id = OrderDoctor::where("order_id",$this->id)->where('status' , 1)->orderBy('created_at','ASC')->value('user_id');
      // $doctor     = Doctor::where('user_id',$doctor_id)->first();
      // return $doctor;

      $doctor_ids = OrderDoctor::limit(2)->where("order_id",$this->id)->where('is_accept' , 1)->orderBy('created_at','ASC')->pluck('user_id')->toArray();
      $doctors     = Doctor::whereIn('user_id',$doctor_ids)->get();
      return $doctors;


    }



    public function getDoctorAttribute()
    {

         $id= OrderDoctor::where("order_id",$this->id)->where("status",3)->value('user_id');

         $user= User::where('id',$id)->select('id','name','email','image','mobile')->first();
         if(count($user) == 0)
         {
         		$user = JWTAuth::parseToken()->authenticate();
         }
         	$doctor = Doctor::where('user_id',$user->id)->first();

    		if($doctor)
    		{
              $user->id = $doctor->id;
    			    $user->bio = $doctor->bio;
    	        $user->title = $doctor->title;
    	        $user->clinic_address = $doctor->clinic_address;
    	        $user->clinic_phone = $doctor->clinic_phone;
    	        $user->website_link = $doctor->website_link;
    		}else{
    			$user->bio = "";
    	        $user->title = "";
    	        $user->clinic_address = "";
    	        $user->clinic_phone = "";
    	        $user->website_link = "";
    		}
    		return $user;

    }

    public function getPatientAttribute()
    {

       $user= User::where('id',$this->user_id)->select('id','name','email','mobile')->first();
       $patient = Patient::where('user_id',$user->id)->first();
    		if($patient)
    		{
    			$user->country = $patient->country;
    	        $user->city = $patient->city;
    	        $user->no_kids = $patient->no_kids;
    		}else{
    			$user->country = "";
    	        $user->city = "";
    	        $user->no_kids = 0;
    		}
    		return $user;

    }


    public function getPatientRequestAttribute()
    {

       $user= User::where('id',$this->user_id)->select('id','name','email','mobile')->first();
       $patient = Patient::where('user_id',$user->id)->first();
        if($patient)
        {
          $user->id = $patient->id;
          $user->country = $patient->country;
              $user->city = $patient->city;
              $user->no_kids = $patient->no_kids;
        }else{
          $user->country = "";
              $user->city = "";
              $user->no_kids = 0;
        }
        return $user;

    }


    public function getPackageTypeAttribute()
    {

       $package_id = UserPackage::where("id",$this->package_id)->value("package_id");
       //$price = Package::where("id",$package_id)->value("price");
		return $package_id;
    }



    public function getcreatedAtAttribute($value)
    {
       return \Carbon\Carbon::parse($value)->format('d F Y h:i A');
    }

}

app/Http/Controllers/OrderController.php
<?php
namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\UserPackage;
use App\CreditDoctor;
use App\PromoCode;
use App\Package;
use App\Order;
use App\User;
use App\OrderDoctor;
use Illuminate\Http\Request;
use DB;
use Carbon\Carbon;
use App\Jobs\SendNotification;
use Illuminate\Support\Facades\Input;
use App\Doctor;

class OrderController extends Controller {

//=============================================================================================================
	#get orders assigned to doctor but not any one accept [DONE]
	public function get_doctor_new_orders(Request $request)
	{
		if(! isset($request->take)){
			$statusCode = 420;
			$response  = array('msg' => 'Invalid Format! ');
	        return response()->json($response, $statusCode);

		}elseif(! isset($request->offset)){
			$statusCode = 420;
			$response  = array('msg' => 'Invalid Format! ');
	        return response()->json($response, $statusCode);

		}else{

			#doctor
			$admin     = (new AuthController)->get_user();
			$order_ids = OrderDoctor::where('user_id',$admin->id)->whereIn('status',[0,1, 7])->pluck('order_id')->toArray();
			#status = 3 order is done
			$orders = Order::whereIn('id',$order_ids)->whereIn('status',[0,1])->skip($request->offset)->take($request->take)->orderBy('created_at', 'DESC')->get();
			$user      = User::where('id',$admin->id)->where('type' , 1)->first();


			if (count($user) > 0) {

				$DoctorOrdersIds = OrderDoctor::where('user_id',$user->id)->pluck('order_id')->toArray();
				$DoctorRate      = Order::whereIn('id' , $DoctorOrdersIds )->where('status',3)->avg('rate');

				$DoctorCredit    = CreditDoctor::where('user_id' , $user->id)->value("calls_credit");
				$DoctorNumCalls  = ( (int)$DoctorCredit ) / 2;
				// $DoctorNumCalls  = Order::whereIn('id' , $DoctorOrdersIds )->where('status',3)->count();
				// $DoctorCredit    = $DoctorNumCalls * 2;

				if ($DoctorRate == null) {
					$DoctorRate = 0;
				}

				$user->doctorRate = round($DoctorRate);
				$user->doctorNumCalls = $DoctorNumCalls;
				$user->doctorCredit = $DoctorCredit;
			}



			if (count($orders)>0) {
				$statusCode = 200;
				$response  = array('msg' => 'done' , 'calls'=>$orders , 'user'=>$user);
		        return response()->json($response, $statusCode);
			}else{
				$statusCode = 201;
				$response  = array('msg' => 'no data','calls'=>$orders , 'user'=>$user);
		        return response()->json($response, $statusCode);
			}

		}

	}
//=============================================================================================================
	#get doctor orders [DONE]
	public function get_doctor_orders(Request $request)
	{
		if(! isset($request->take)){
			$statusCode = 420;
			$response  = array('msg' => 'Invalid Format! ');
	        return response()->json($response, $statusCode);

		}elseif(! isset($request->offset)){
			$statusCode = 420;
			$response  = array('msg' => 'Invalid Format! ');
	        return response()->json($response, $statusCode);

		}else{
			#doctor
			$admin = (new AuthController)->get_user();
			$order_ids=OrderDoctor::where('user_id',$admin->id)->whereIn('status',[2,3,4,7])->pluck('order_id')->toArray();

			#status = 3 order is done
			$orders = Order::whereIn('id',$order_ids)->skip($request->offset)->take($request->take)->orderBy('created_at','DESC')->get();
			if (count($orders)>0) {
				$statusCode = 200;
				$response  = array('msg' => 'done','calls'=>$orders);
		        return response()->json($response, $statusCode);
			}else{
				$statusCode = 201;
				$response  = array('msg' => 'no data','calls'=>$orders);
		        return response()->json($response, $statusCode);
			}

		}

	}



	#get patient orders [DONE]
	public function get_patient_orders(Request $request)
	{
		if(! isset($request->take)){
			$statusCode = 420;
			$response  = array('msg' => 'Invalid Format! ');
	        return response()->json($response, $statusCode);

		}elseif(! isset($request->offset)){
			$statusCode = 420;
			$response  = array('msg' => 'Invalid Format! ');
	        return response()->json($response, $statusCode);

		}else{
			#patient
			$admin = (new AuthController)->get_user();
			#status = 3 order is done
			$orders = Order::where('user_id',$admin->id)->whereIn('status',[2, 3, 4, 6, 7])->skip($request->offset)->take($request->take)->orderBy('created_at','DESC')->get();



			if (count($orders)>0) {
				$statusCode = 200;
				$response  = array('msg' => 'done','calls'=>$orders);
		        return response()->json($response, $statusCode);
			}else{
				$statusCode = 201;
				$response  = array('msg' => 'no data','calls'=>$orders);
		        return response()->json($response, $statusCode);
			}

		}

	}
//================================================================================================================================
	public function index()
	{
		$orders = Order::orderBy('id', 'desc')->paginate(20);
		//dd($orders[10]->doctor_accept);
		$user = 0;
		return view('orders.index', compact('user','orders'));
	}
//================================================================================================================================
	public function filterOrders()
	{

		if (Input::get('user_id') == 0) {

			if (Input::get('statusChoice') == 0) {
				return redirect()->to('orders');
			}

			if (Input::get('created_at') != null && Input::get('statusChoice') != null) {

				$CarbonFormate = explode("-", Input::get('created_at'));
				$created_at = Carbon::create($CarbonFormate[0],$CarbonFormate[1],$CarbonFormate[2],0)->format('Y-m-d');
				$orders = Order::whereDate('created_at' , '=' , $created_at)->where('status' , Input::get('statusChoice'))->orderBy('id', 'DESC')->get();

			}elseif (Input::get('created_at') == null && Input::get('statusChoice') != null) {

				$orders = Order::where('status' , Input::get('statusChoice'))->orderBy('id', 'DESC')->get();

			}elseif (Input::get('created_at') != null && Input::get('statusChoice') == null) {

				$CarbonFormate = explode("-", Input::get('created_at'));
				$created_at    = Carbon::create($CarbonFormate[0],$CarbonFormate[1],$CarbonFormate[2],0)->format('Y-m-d');
				$orders        = Order::whereDate('created_at' , '=' , $created_at)->orderBy('id', 'DESC')->get();
			}

		}else{

			// $userDetails = User::where('id' , $user_id)->first();

			// if ($userDetails->type == 0) { #patients order

			// 	if ($status == -1) {

			// 		$orders = Order::where('user_id' , $user_id)->orderBy('id', 'DESC')->get();

			// 	}elseif ($status == 4) {

			// 		$orders = Order::where('user_id' , $user_id)->whereIn('status' , [4,6])->orderBy('id', 'DESC')->get();

			// 	}else{

			// 		$orders = Order::where('user_id' , $user_id)->where('status' , $status)->orderBy('id', 'DESC')->get();
			// 	}

			// }else{ #doctor orders


			// 	if ($status == -1) {

			// 		$DoctorOrdersIds  = OrderDoctor::where('user_id',$user_id)->pluck('order_id')->toArray();
			// 		$orders = Order::whereIn('id' , $DoctorOrdersIds )->orderBy('id', 'DESC')->get();


			// 	}elseif ($status == 4) {

			// 		$DoctorOrdersIds  = OrderDoctor::where('user_id',$user_id)->whereIn('status' , [4,6])->pluck('order_id')->toArray();
			// 		$orders = Order::whereIn('id' , $DoctorOrdersIds )->whereIn('status' , [4,6])->orderBy('id', 'DESC')->get();

			// 	}else{

			// 		$DoctorOrdersIds  = OrderDoctor::where('user_id',$user_id)->where('status' , $status)->pluck('order_id')->toArray();
			// 		$orders = Order::whereIn('id' , $DoctorOrdersIds )->where('status' , $status)->orderBy('id', 'DESC')->get();

			// 	}

			// }
		}

		$user = Input::get('user_id');
		$status = Input::get('statusChoice');
		//dd($orders[10]->doctor_accept);
		return view('orders.index', compact('user', 'orders', 'status'));
	}
//================================================================================================================================
	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('orders.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store(Request $request)
	{
		$order = new Order();

		$order->user_id = $request->input("user_id");
        $order->rate = $request->input("rate");
        $order->review = $request->input("review");
        $order->status = $request->input("status");
        $order->doctor_notes = $request->input("doctor_notes");
        $order->doctor_report_problem = $request->input("doctor_report_problem");
        $order->package_id = $request->input("package_id");
        $order->kid_name = $request->input("kid_name");
        $order->kid_birthdate = $request->input("kid_birthdate");
        $order->kid_gender = $request->input("kid_gender");
        $order->complain = $request->input("complain");
        $order->patient_notes = $request->input("patient_notes");
        $order->duration_call = $request->input("duration_call");

		$order->save();

		return redirect()->route('orders.index')->with('message', 'Item created successfully.');
	}

//============================================================================================================================
#accept_order [DONE]
	public function accept_order(Request $request)
	{
		if(! isset($request->order_id)){
			$statusCode = 420;
			$response  = array('msg' => 'Invalid Format! ');
	        return response()->json($response, $statusCode);

		}else{
			#doctor that accept request
			$admin = (new AuthController)->get_user();
			$order = Order::where('id', $request->order_id)->first();
			//dd($order->status);
			if(! $order){
				$statusCode = 421;
				$response  = array('msg' => 'This request does not exist! ');
		        return response()->json($response, $statusCode);

			}elseif($order->status != 0){

				$statusCode = 422;
				$response  = array('msg' => 'This request does already taken by another doctor! ');

resources/views/orders/index.blade.php
<?php
use App\User;
use App\Package;
use App\PromoCode;
use Carbon\Carbon;
?>
@extends('layouts.admin')

@section('header')
    <div class="page-header clearfix">

        <form action="{{ url('filterOrders') }}" method="GET" style="display: inline;">

            <input class="btn-group" type="hidden" name="user_id" value="{{$user}}">
            <input class="btn-group" type="date"   name="created_at" value="">

            <select class="btn-group" name="statusChoice">
                <?php $statuses = [0 => 'All', 10 => 'Not Accepted', 1 => 'Accepted', 4 => 'Cancelled', 2 => 'No Respond', 3 => 'Finished']; ?>
                @foreach($statuses as $key => $value)
                    <option value="{{ $key }}" {{ (isset($status) && $key == $status) ? 'selected' : '' }}> {{ $value }} </option>
                @endforeach
            </select>

            <div class="btn-group" role="group" aria-label="...">
                <button type="submit" class="btn btn-primary ">Filter</button>
            </div>
        </form>

    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            @if($orders->count())
                <table id="" class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <td>Patient Name</td>
                            <th>provisional Diagnosis</th>
                            <th>Doctor Notes</th>
                            <td>Doctors On Shift</td>
                            <td>Doctor Accept</td>
                            <th>RATE</th>
                            <th>STATUS</th>
                            <th>Package Name</th>
                            <th>Promo Code</th>
                            <th>Delivery Status</th>
                            <th>Created_at</th>
                            <th>Accepted_at</th>
                            <th class="text-right">OPTIONS</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($orders as $order)
                            <tr>
                                <td>{{$order->id}}</td>
                                <td><a href="{{ route('patients.show', $order->patient_request->id) }}">{{$order->patient_request->name}}</a></td>
                                <td>{{$order->doctor_report_problem}}</td>
                                <td>{{$order->doctor_notes}}</td>
                                <td>

                                @foreach($order->doctors_on_shift as $doctors)

                                        <a href="{{ route('doctors.show', $doctors->id) }}"> <?php echo User::where('id' , $doctors->user_id )->value("name"); ?></a><br>

                                @endforeach
                                </td>

                                <td>
                                @foreach($order->doctor_accept as $accept_doctor)
                                    <a href="{{ route('doctors.show', $accept_doctor->id) }}"> <?php echo User::where('id' , $accept_doctor->user_id )->value("name"); ?></a><br>
                                @endforeach
                                </td>

                                <td>{{$order->rate}}</td>
                                <?php

                                    if ($order->status == 0) {
                                       echo "<td> not accepted </td>";
                                    }elseif ($order->status == 1) {
                                        echo "<td> accepted </td>";
                                    }elseif ($order->status == 4 OR $order->status == 6) {
                                        echo "<td> cancelled </td>";
                                    }elseif ($order->status == 3) {
                                        echo "<td> Finished </td>";
                                    }elseif ($order->status == 2) {
                                        echo "<td> no respond </td>";
                                    }else{
                                        echo "<td>  </td>";
                                    }

                                ?>
                                <td><a  href="{{ route('packages.show', $order->packageType) }}">{{ Package::where('id' , $order->packageType )->value("name") }}</a></td>
                                <td><a  href="{{ route('promo_codes.show', $order->promo_code_id) }}">{{ PromoCode::where('id' , $order->promo_code_id )->value("code") }}</a></td>
                                <td>{{$order->deliveryStatus}}</td>
                                <td>{{$order->created_at}}</td>
                                <td><?php if($order->accepted_at){echo \Carbon\Carbon::parse($order->accepted_at)->format('d F Y h:i A'); } ?></td>
                                <td class="text-right">
                                    <a class="btn btn-xs btn-primary" href="{{ route('orders.show', $order->id) }}"><i class="glyphicon glyphicon-eye-open"></i> View</a><br><br>
                                    <a class="btn btn-xs btn-warning" href="{{ route('orders.edit', $order->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a><br><br>
                                    <form action="{{ route('orders.destroy', $order->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
		<div class="text-center">
			{{ $orders->links() }}
		</div>
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif

        </div>
    </div>

@endsection

resources/views/orders/show.blade.php
@extends('layouts.admin')
@section('header')
<div class="page-header">
        <h1>Orders / Show #{{$order->id}}</h1>
        <form action="{{ route('orders.destroy', $order->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="btn-group pull-right" role="group" aria-label="...">
                <a class="btn btn-warning btn-group" role="group" href="{{ route('orders.edit', $order->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">

            <form action="#">
                <div class="form-group col-md-4">
                    <label for="nome">ID</label>
                    <p class="form-control-static">{{$order->id}}</p>
                </div>
                <div class="form-group col-md-4">
                     <label for="user_id">USER_ID</label>
                     <p class="form-control-static">{{$order->user_id}}</p>
                </div>
                    <div class="form-group col-md-4">
                     <label for="rate">RATE</label>
                     <p class="form-control-static">{{$order->rate}}</p>
                </div>
                    <div class="form-group col-md-4">
                     <label for="review">REVIEW</label>
                     <p class="form-control-static">{{$order->review}}</p>
                </div>
                    <div class="form-group col-md-4">
                     <label for="status">STATUS</label>
                     <p class="form-control-static">
                        <?php 
                            if ($order->status == 0) {
                               echo "<td> new request </td>";
                            }elseif ($order->status == 1) {
                                echo "<td> request accepted </td>";
                            }elseif ($order->status == 4 OR $order->status == 6) {
                                echo "<td> request canceled </td>";
                            }elseif ($order->status == 3) {
                                echo "<td> call ended </td>";
                            }elseif ($order->status == 2) {
                                echo "<td> call not respond </td>";
                            }elseif ($order->status == 5) {
                                echo "<td> on call </td>";
                            }
                        ?>                         
                     </p>
                </div>
                    <div class="form-group col-md-4">
                     <label for="doctor_notes">DOCTOR_NOTES</label>
                     <p class="form-control-static">{{$order->doctor_notes}}</p>
                </div>
                    <div class="form-group col-md-4">
                     <label for="doctor_report_problem">Provisional Diagnosis</label>
                     <p class="form-control-static">{{$order->doctor_report_problem}}</p>
                </div>
                    <div class="form-group col-md-4">
                     <label for="package_id">PACKAGE_ID</label>
                     <p class="form-control-static">{{$order->package_id}}</p>
                </div>
                    <div class="form-group col-md-4">
                     <label for="kid_name">KID_NAME</label>
                     <p class="form-control-static">{{$order->kid_name}}</p>
                </div>
                    <div class="form-group col-md-4">
                     <label for="kid_birthdate">KID_BIRTHDATE</label>
                     <p class="form-control-static">{{$order->kid_birthdate}}</p>
                </div>
                    <div class="form-group col-md-4">
                     <label for="kid_gender">KID_GENDER</label>
                     <p class="form-control-static">{{$order->kid_gender}}</p>
                </div>
                    <div class="form-group col-md-4">
                     <label for="complain">COMPLAIN</label>
                     <p class="form-control-static">{{$order->complain}}</p>
                </div>
                    <div class="form-group col-md-4">
                     <label for="patient_notes">PATIENT_NOTES</label>
                     <p class="form-control-static">{{$order->patient_notes}}</p>
                </div>
                </div>
                    <div class="form-group">
                     <label for="status" class="control-label">Created at</label>
                     <p class="form-control-static">{{$order->created_at}}</p>
                </div>
                </div>
                    <div class="form-group">
                     <label for="status" class="control-label">Finished at</label>
                     <p class="form-control-static">{{$order->finished_at}}</p>
                </div>
            </form>

            <a class="btn btn-link" href="{{ route('orders.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>

        </div>
    </div>

@endsection